# Generated by Django 2.0 on 2019-07-23 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hdbwatermeterday',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='meterparameter',
            options={'managed': True},
        ),
    ]
