# Generated by Django 2.1.1 on 2018-09-13 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bigmeter',
            options={'managed': True},
        ),
    ]
