# Generated by Django 2.1 on 2018-09-13 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dmam', '0001_initial'),
        ('legacy', '0002_auto_20180913_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='bigmeter',
            name='districtid',
            field=models.IntegerField(blank=True, db_column='DistrictId', null=True),
        ),
        migrations.AddField(
            model_name='bigmeter',
            name='station',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='dmam.Station'),
        ),
    ]
