# Generated by Django 2.0 on 2019-07-24 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0002_auto_20190723_1538'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bigmeter',
            options={'managed': True},
        ),
    ]
