# Generated by Django 2.1.1 on 2018-09-13 16:27

from django.db import migrations


def fill_station(apps, schema_editor):
    '''
    We can't import the Post model directly as it may be a newer
    version than this migration expects. We use the historical version.
    '''
    Bigmeter = apps.get_model('legacy', 'Bigmeter')
    Station = apps.get_model('dmam', 'Station')

    for b in Bigmeter.objects.all():
        commaddr=b.commaddr
        s=Station.objects.get(commaddr=commaddr)
        if s:
            print(s.username)
        b.station = s
        b.save()


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0002_auto_20180913_1611'),
    ]

    operations = [
        migrations.RunPython(fill_station),
    ]
