# Generated by Django 2.1 on 2018-09-13 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0003_auto_20180913_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigmeter',
            name='station',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dmam.Station'),
        ),
    ]
