# Generated by Django 2.0 on 2019-07-26 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0003_auto_20190724_1425'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alarm',
            options={'managed': True},
        ),
    ]
