# Generated by Django 2.0 on 2018-09-19 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0004_auto_20180913_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bigmeter',
            name='station',
        ),
    ]
