# Generated by Django 2.0 on 2018-10-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0005_remove_bigmeter_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bigmeter2',
            fields=[
                ('username', models.CharField(blank=True, db_column='UserName', max_length=30, null=True)),
                ('usertype', models.CharField(blank=True, db_column='UserType', max_length=128, null=True)),
                ('userid', models.CharField(blank=True, db_column='UserId', max_length=128, null=True)),
                ('installationsite', models.CharField(blank=True, db_column='InstallationSite', max_length=128, null=True)),
                ('metertype', models.CharField(blank=True, db_column='MeterType', max_length=30, null=True)),
                ('manufacturer', models.CharField(blank=True, db_column='Manufacturer', max_length=30, null=True)),
                ('model', models.CharField(blank=True, db_column='Model', max_length=30, null=True)),
                ('dn', models.CharField(blank=True, db_column='Dn', max_length=30, null=True)),
                ('material', models.CharField(blank=True, db_column='Material', max_length=30, null=True)),
                ('serialnumber', models.CharField(blank=True, db_column='SerialNumber', max_length=30, null=True)),
                ('madedate', models.CharField(blank=True, db_column='MadeDate', max_length=30, null=True)),
                ('lng', models.CharField(blank=True, db_column='Lng', max_length=30, null=True)),
                ('lat', models.CharField(blank=True, db_column='Lat', max_length=30, null=True)),
                ('coortype', models.CharField(blank=True, db_column='CoorType', max_length=30, null=True)),
                ('commaddr', models.CharField(db_column='CommAddr', max_length=30, primary_key=True, serialize=False)),
                ('simid', models.CharField(blank=True, db_column='SIMID', max_length=30, null=True)),
                ('districtid', models.IntegerField(blank=True, db_column='DistrictId', null=True)),
                ('field_metabinding', models.CharField(blank=True, db_column='\r\nMetaBinding', max_length=20, null=True)),
                ('gpflow', models.CharField(blank=True, db_column='GPFlow', max_length=64, null=True)),
                ('uplimitflow', models.CharField(blank=True, db_column='UpLimitFlow', max_length=64, null=True)),
                ('monthupflow', models.CharField(blank=True, db_column='MonthUpFlow', max_length=64, null=True)),
                ('monthdownflow', models.CharField(blank=True, db_column='MonthDownFlow', max_length=64, null=True)),
                ('commstate', models.IntegerField(blank=True, db_column='CommState', null=True)),
                ('meterstate', models.CharField(blank=True, db_column='MeterState', max_length=30, null=True)),
                ('gprsv', models.CharField(blank=True, db_column='GprsV', max_length=30, null=True)),
                ('meterv', models.CharField(blank=True, db_column='MeterV', max_length=30, null=True)),
                ('downlimitv', models.CharField(blank=True, db_column='DownLimitV', max_length=30, null=True)),
                ('t', models.CharField(blank=True, db_column='T', max_length=30, null=True)),
                ('hearttime', models.CharField(blank=True, db_column='HeartTime', max_length=30, null=True)),
                ('signlen', models.CharField(blank=True, db_column='SignLen', max_length=30, null=True)),
                ('lastonlinetime', models.CharField(blank=True, db_column='LastOnLineTime', max_length=30, null=True)),
                ('createdate', models.CharField(blank=True, db_column='CreateDate', max_length=30, null=True)),
                ('alarmoffline', models.IntegerField(blank=True, db_column='AlarmOffLine', null=True)),
                ('alarmonline', models.IntegerField(blank=True, db_column='AlarmOnLine', null=True)),
                ('alarmgprsvlow', models.IntegerField(blank=True, db_column='AlarmGprsVLow', null=True)),
                ('alarmmetervlow', models.IntegerField(blank=True, db_column='AlarmMeterVLow', null=True)),
                ('alarmuplimitflow', models.IntegerField(blank=True, db_column='AlarmUpLimitFlow', null=True)),
                ('alarmgpflow', models.IntegerField(blank=True, db_column='AlarmGPFlow', null=True)),
                ('pressure', models.CharField(blank=True, db_column='Pressure', max_length=64, null=True)),
                ('plustotalflux', models.CharField(blank=True, db_column='PlusTotalFlux', max_length=64, null=True)),
                ('reversetotalflux', models.CharField(blank=True, db_column='ReverseTotalFlux', max_length=64, null=True)),
                ('flux', models.CharField(blank=True, db_column='Flux', max_length=64, null=True)),
                ('totalflux', models.CharField(blank=True, db_column='TotalFlux', max_length=64, null=True)),
                ('pressurereadtime', models.CharField(blank=True, db_column='PressureReadTime', max_length=30, null=True)),
                ('fluxreadtime', models.CharField(blank=True, db_column='FluxReadTime', max_length=30, null=True)),
                ('pressurealarm', models.IntegerField(blank=True, db_column='PressureAlarm', null=True)),
                ('pressureup', models.CharField(blank=True, db_column='PressureUp', max_length=64, null=True)),
                ('pressuredown', models.CharField(blank=True, db_column='PressureDown', max_length=64, null=True)),
                ('dosagealarm', models.IntegerField(blank=True, db_column='DosageAlarm', null=True)),
                ('dosageup', models.CharField(blank=True, db_column='DosageUp', max_length=64, null=True)),
                ('dosagedown', models.CharField(blank=True, db_column='DosageDown', max_length=64, null=True)),
            ],
            options={
                'db_table': 'bigmeter',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='bigmeter',
            name='pickperiod',
            field=models.CharField(blank=True, db_column='PickPeriod', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='bigmeter',
            name='reportperiod',
            field=models.CharField(blank=True, db_column='ReportPeriod', max_length=64, null=True),
        ),
    ]
