# Generated by Django 2.0 on 2018-10-18 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0006_auto_20181017_1717'),
        ('legacy', '0006_auto_20181017_2102'),
    ]

    operations = [
    ]
