# Generated by Django 2.0 on 2018-11-01 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0007_merge_20181018_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commaddr', models.CharField(db_column='CommAddr', max_length=30, unique=True)),
                ('serialnumber', models.CharField(blank=True, db_column='Serialnumber', max_length=30, null=True)),
                ('tcpresendcount', models.CharField(blank=True, db_column='tcpresendcount', max_length=64, null=True)),
                ('tcpresponovertime', models.CharField(blank=True, db_column='tcpresponovertime', max_length=64, null=True)),
                ('udpresendcount', models.CharField(blank=True, db_column='udpresendcount', max_length=64, null=True)),
                ('udpresponovertime', models.CharField(blank=True, db_column='udpresponovertime', max_length=64, null=True)),
                ('smsresendcount', models.CharField(blank=True, db_column='smsresendcount', max_length=64, null=True)),
                ('smsresponovertime', models.CharField(blank=True, db_column='smsresponovertime', max_length=64, null=True)),
                ('heartbeatperiod', models.CharField(blank=True, db_column='heartbeatperiod', max_length=64, null=True)),
                ('ipaddr', models.CharField(blank=True, db_column='ipaddr', max_length=64, null=True)),
                ('port', models.CharField(blank=True, db_column='port', max_length=64, null=True)),
                ('entrypoint', models.CharField(blank=True, db_column='entrypoint', max_length=64, null=True)),
                ('updatastarttime', models.CharField(blank=True, db_column='updatastarttime', max_length=64, null=True)),
                ('updatamode', models.CharField(blank=True, db_column='updatamode', max_length=64, null=True)),
                ('collectperiod', models.CharField(blank=True, db_column='collectperiod', max_length=64, null=True)),
                ('updataperiod', models.CharField(blank=True, db_column='updataperiod', max_length=64, null=True)),
                ('updatatime1', models.CharField(blank=True, db_column='updatatime1', max_length=64, null=True)),
                ('updatatime2', models.CharField(blank=True, db_column='updatatime2', max_length=64, null=True)),
                ('updatatime3', models.CharField(blank=True, db_column='updatatime3', max_length=64, null=True)),
                ('updatatime4', models.CharField(blank=True, db_column='updatatime4', max_length=64, null=True)),
                ('dn', models.CharField(blank=True, db_column='dn', max_length=64, null=True)),
                ('transimeterfactor', models.CharField(blank=True, db_column='transimeterfactor', max_length=64, null=True)),
                ('manufacturercode', models.CharField(blank=True, db_column='manufacturercode', max_length=64, null=True)),
                ('flowzerovalue', models.CharField(blank=True, db_column='flowzerovalue', max_length=64, null=True)),
                ('smallsignalcutpoint', models.CharField(blank=True, db_column='smallsignalcutpoint', max_length=64, null=True)),
                ('pressurepermit', models.CharField(blank=True, db_column='pressurepermit', max_length=64, null=True)),
                ('flowdorient', models.CharField(blank=True, db_column='flowdorient', max_length=64, null=True)),
                ('maintaindate', models.CharField(blank=True, db_column='maintaindate', max_length=64, null=True)),
                ('plusaccumupreset', models.CharField(blank=True, db_column='plusaccumupreset', max_length=64, null=True)),
                ('flowmeasureunit', models.CharField(blank=True, db_column='flowmeasureunit', max_length=64, null=True)),
            ],
            options={
                'db_table': 'meterparameter',
                'managed': True,
            },
        ),
    ]
