# Generated by Django 2.0 on 2018-11-02 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0008_meterparameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='meterparameter',
            name='readparametertime',
            field=models.CharField(blank=True, db_column='readparametertime', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='meterparameter',
            name='sendparametertime',
            field=models.CharField(blank=True, db_column='sendparametertime', max_length=64, null=True),
        ),
    ]
