# Generated by Django 2.0 on 2018-11-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0009_auto_20181102_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='meterparameter',
            name='biaofactor',
            field=models.CharField(blank=True, db_column='biaofactor', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='meterparameter',
            name='isflowzerovalue',
            field=models.CharField(blank=True, db_column='isflowzerovalue', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='meterparameter',
            name='issmallsignalcutpoint',
            field=models.CharField(blank=True, db_column='issmallsignalcutpoint', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='meterparameter',
            name='liciperoid',
            field=models.CharField(blank=True, db_column='liciperoid', max_length=64, null=True),
        ),
    ]
