# Generated by Django 2.0 on 2018-12-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0010_auto_20181106_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='meterparameter',
            name='commandstate',
            field=models.CharField(blank=True, db_column='commandstate', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='meterparameter',
            name='commandtype',
            field=models.CharField(blank=True, db_column='commandtype', max_length=64, null=True),
        ),
    ]
