# Generated by Django 2.0 on 2019-01-22 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0011_auto_20181214_0931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hdbwatermeterday',
            options={'managed': True},
        ),
    ]
