# Generated by Django 2.0 on 2019-05-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0012_auto_20190122_1531'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='hdbwatermeterday',
            index=models.Index(fields=['waterid', 'communityid'], name='hdb_waterme_WaterId_c16e94_idx'),
        ),
        migrations.AddIndex(
            model_name='hdbwatermeterday',
            index=models.Index(fields=['-hdate'], name='hdb_waterme_HDate_993673_idx'),
        ),
    ]
