# Generated by Django 2.0.8 on 2018-08-19 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personalized',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loginLogo', models.ImageField(upload_to='resources/img/logo/')),
                ('webIco', models.ImageField(upload_to='resources/img/logo/')),
                ('homeLogo', models.ImageField(upload_to='resources/img/logo/')),
                ('topTitle', models.CharField(blank=True, max_length=256, null=True)),
                ('copyright', models.CharField(blank=True, max_length=256, null=True)),
                ('websiteName', models.CharField(blank=True, max_length=256, null=True)),
                ('recordNumber', models.CharField(blank=True, max_length=256, null=True)),
                ('frontPageMsg', models.CharField(blank=True, max_length=256, null=True)),
                ('frontPageMsgUrl', models.CharField(blank=True, max_length=256, null=True)),
                ('updateDataUsername', models.CharField(blank=True, max_length=256, null=True)),
                ('updateDataTime', models.DateTimeField(auto_now=True, db_column='updateDataTime')),
                ('belongto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entm.Organizations')),
            ],
            options={
                'managed': True,
                'db_table': 'personalized',
            },
        ),
    ]
