# Generated by Django 2.0.5 on 2018-08-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personalized',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logoPagesPhoto', models.ImageField(upload_to='resources/img/logo/')),
                ('WebIco', models.ImageField(upload_to='resources/img/logo/')),
                ('indexPagesPhoto', models.ImageField(upload_to='resources/img/logo/')),
                ('topTitleMsg', models.CharField(blank=True, max_length=256, null=True)),
                ('bottomTitleMsg', models.CharField(blank=True, max_length=256, null=True)),
                ('frontPageMsg', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'personalized',
                'managed': True,
            },
        ),
    ]
