# Generated by Django 2.0.5 on 2018-08-15 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entm', '0001_initial'),
        ('sysm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalized',
            name='belongto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entm.Organizations'),
        ),
    ]
