# Generated by Django 2.1 on 2018-08-26 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalized',
            name='ptype',
            field=models.CharField(default='default', max_length=10),
            preserve_default=False,
        ),
    ]
