# Generated by Django 2.0.5 on 2018-08-15 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysm', '0002_personalized_belongto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalized',
            old_name='bottomTitleMsg',
            new_name='copyright',
        ),
        migrations.RenameField(
            model_name='personalized',
            old_name='WebIco',
            new_name='homeLogo',
        ),
        migrations.RenameField(
            model_name='personalized',
            old_name='indexPagesPhoto',
            new_name='loginLogo',
        ),
        migrations.RenameField(
            model_name='personalized',
            old_name='topTitleMsg',
            new_name='recordNumber',
        ),
        migrations.RenameField(
            model_name='personalized',
            old_name='logoPagesPhoto',
            new_name='webIco',
        ),
        migrations.AddField(
            model_name='personalized',
            name='topTitle',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='personalized',
            name='websiteName',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
