# Generated by Django 2.0.5 on 2018-08-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysm', '0002_personalized_ptype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalized',
            name='homeLogo',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='personalized',
            name='loginLogo',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='personalized',
            name='webIco',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
