# Generated by Django 2.0.5 on 2018-08-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysm', '0003_auto_20180815_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalized',
            name='frontPageMsgUrl',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='personalized',
            name='updateDataTime',
            field=models.DateTimeField(auto_now=True, db_column='updateDataTime'),
        ),
        migrations.AddField(
            model_name='personalized',
            name='updateDataUsername',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
