# Generated by Django 2.0 on 2018-06-03 14:05

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    # dependencies = [
    #     ('auth', '0009_alter_user_last_name_max_length'),
    # ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_name', models.CharField(max_length=30, unique=True, verbose_name='user name')),
                ('real_name', models.CharField(blank=True, max_length=30, verbose_name='real name')),
                ('sex', models.CharField(blank=True, max_length=30, verbose_name='Sex')),
                ('phone_number', models.CharField(blank=True, max_length=30, verbose_name='phone number')),
                ('belongto', models.CharField(blank=True, max_length=30, verbose_name='belongs to')),
                ('expire_date', models.CharField(blank=True, max_length=30, verbose_name='Expired date')),
                ('Role', models.CharField(blank=True, max_length=30, verbose_name='Role')),
                ('email', models.EmailField(blank=True, max_length=255, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MyRoles',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.Group')),
                ('notes', models.CharField(blank=True, max_length=156)),
                ('permissionTree', models.CharField(blank=True, max_length=5000)),
            ],
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
