# Generated by Django 2.0 on 2019-05-05 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entm', '0005_organizations_organlevel'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signin_time', models.DateTimeField(auto_now=True, db_column='signin time')),
                ('ip', models.CharField(blank=True, max_length=32, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=256, null=True)),
                ('log_from', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.TextField(blank=True)),
                ('belongto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entm.Organizations')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'loginrecord',
                'managed': True,
            },
        ),
    ]
