# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-19 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name=b'email address')),
                ('user_name', models.CharField(blank=True, max_length=30, verbose_name='user name')),
                ('real_name', models.CharField(blank=True, max_length=30, verbose_name='real name')),
                ('sex', models.CharField(blank=True, max_length=30, verbose_name='Sex')),
                ('phone_number', models.CharField(blank=True, max_length=30, verbose_name='phone number')),
                ('belongto', models.CharField(blank=True, max_length=30, verbose_name='belongs to')),
                ('expire_date', models.CharField(blank=True, max_length=30, verbose_name='Expired date')),
                ('Role', models.CharField(blank=True, max_length=30, verbose_name='Role')),
                ('active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
