# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-04 09:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myroles',
            managers=[
            ],
        ),
    ]
