# Generated by Django 2.0 on 2018-06-09 01:22

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180604_0945'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myroles',
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
    ]
