# Generated by Django 2.0 on 2018-06-19 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180618_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='myroles',
            name='uid',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
