# Generated by Django 2.0 on 2018-06-20 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entm', '0001_initial'),
        ('accounts', '0003_myroles_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='myroles',
            name='belongto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='entm.Organizations'),
        ),
    ]
