# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-11 17:22
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180610_2147'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myroles',
            managers=[
                ('objects', accounts.models.MyRolesManager()),
            ],
        ),
        migrations.AddField(
            model_name='myroles',
            name='rid',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
