# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-25 09:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180425_0937'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Roles',
            new_name='MyRoles',
        ),
    ]
