# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-25 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180425_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=255, verbose_name=b'email address'),
        ),
    ]
