# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-26 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(choices=[(True, b'\xe5\x90\xaf\xe7\x94\xa8'), (False, b'\xe5\x81\x9c\xe6\xad\xa2')], default=True),
        ),
    ]
