# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-25 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20180522_2208'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myroles',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='myroles',
            name='permissionTree',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
