# Generated by Django 2.0 on 2019-07-23 15:24

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FenceDistrict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='区域名称')),
                ('ftype', models.CharField(blank=True, max_length=30, null=True, verbose_name='区域类型')),
                ('createDataTime', models.CharField(blank=True, max_length=30, null=True, verbose_name='创建时间')),
                ('updateDataTime', models.CharField(blank=True, max_length=30, null=True, verbose_name='修改时间')),
                ('createDataUsername', models.CharField(blank=True, max_length=30, null=True, verbose_name='创建人')),
                ('updateDataUsername', models.CharField(blank=True, max_length=30, null=True, verbose_name='修改人')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('cid', models.CharField(blank=True, max_length=100, null=True)),
                ('pId', models.CharField(blank=True, max_length=100, null=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('belongto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entm.Organizations')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='ggis.FenceDistrict')),
            ],
            options={
                'db_table': 'virvo_fencedistrict',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FenceShape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shapeId', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='区域名称')),
                ('zonetype', models.CharField(blank=True, max_length=30, null=True, verbose_name='区域类型')),
                ('shape', models.CharField(blank=True, max_length=30, null=True, verbose_name='形状')),
                ('geomdata', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=0)),
                ('geomjson', models.TextField(blank=True, null=True)),
                ('pointSeqs', models.TextField()),
                ('longitudes', models.TextField()),
                ('latitudes', models.TextField()),
                ('lnglatQuery_LU', models.CharField(blank=True, max_length=30, null=True)),
                ('lnglatQuery_RD', models.CharField(blank=True, max_length=30, null=True)),
                ('centerPointLat', models.CharField(blank=True, max_length=30, null=True)),
                ('centerPointLng', models.CharField(blank=True, max_length=30, null=True)),
                ('centerRadius', models.CharField(blank=True, max_length=30, null=True)),
                ('province', models.CharField(blank=True, max_length=30, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('district', models.CharField(blank=True, max_length=30, null=True)),
                ('administrativeLngLat', models.TextField()),
                ('strokeColor', models.CharField(blank=True, max_length=100, null=True)),
                ('fillColor', models.CharField(blank=True, max_length=100, null=True)),
                ('dma_no', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'virvo_fenceshape',
                'managed': True,
            },
        ),
    ]
