# Generated by Django 2.0 on 2019-05-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ggis', '0003_auto_20181114_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='fenceshape',
            name='geomjson',
            field=models.TextField(blank=True, null=True),
        ),
    ]
