# Generated by Django 2.0 on 2019-05-29 13:44

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ggis', '0005_fenceshape_geomdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='fenceshape',
            name='polygon',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, default='POLYGON EMPTY', srid=4326),
            preserve_default=False,
        ),
    ]
