# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-12 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, null=True, verbose_name='\u7ec4\u7ec7\u673a\u6784\u540d\u79f0')),
                ('attribute', models.CharField(blank=True, max_length=300, null=True, verbose_name='\u7ec4\u7ec7\u673a\u6784\u6027\u8d28')),
                ('register_date', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u6ce8\u518c\u65e5\u671f')),
                ('owner_name', models.CharField(blank=True, max_length=300, null=True, verbose_name='\u8d1f\u8d23\u4eba')),
                ('phone_number', models.CharField(blank=True, max_length=300, null=True, verbose_name='\u7535\u8bdd\u53f7\u7801')),
                ('firm_address', models.CharField(blank=True, max_length=300, null=True, verbose_name='\u5730\u5740')),
                ('cid', models.CharField(blank=True, max_length=300, null=True)),
                ('pId', models.CharField(blank=True, max_length=300, null=True)),
                ('is_org', models.BooleanField(max_length=300)),
                ('uuid', models.CharField(blank=True, max_length=300, null=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='entm.Organizations')),
            ],
            options={
                'db_table': 'organizations',
                'managed': True,
                'permissions': (('perms_datamonitor', '\u6570\u636e\u76d1\u63a7'), ('mapmonitor_perms_datamonitor', '\u5730\u56fe\u76d1\u63a7'), ('mapmonitor_perms_datamonitor_edit', '\u5730\u56fe\u76d1\u63a7_\u53ef\u5199'), ('realcurlv_perms_datamonitor', '\u5b9e\u65f6\u66f2\u7ebf'), ('realcurlv_perms_datamonitor_edit', '\u5b9e\u65f6\u66f2\u7ebf_\u53ef\u5199'), ('realdata_perms_datamonitor', '\u5b9e\u65f6\u6570\u636e'), ('realdata_perms_datamonitor_edit', '\u5b9e\u65f6\u6570\u636e_\u53ef\u5199'), ('dmaonline_perms_datamonitor', 'DMA\u5728\u7ebf\u76d1\u63a7'), ('dmaonline_perms_datamonitor_edit', 'DMA\u5728\u7ebf\u76d1\u63a7_\u53ef\u5199'), ('perms_datanalys', '\u6570\u636e\u5206\u6790'), ('dailyuse_perms_datanalys', '\u65e5\u7528\u6c34\u5206\u6790'), ('dailyuse_perms_datanalys_edit', '\u65e5\u7528\u6c34\u5206\u6790_\u53ef\u5199'), ('monthlyuse_perms_datanalys', '\u6708\u7528\u6c34\u5206\u6790'), ('monthlyuse_perms_datanalys_edit', '\u6708\u7528\u6c34\u5206\u6790_\u53ef\u5199'), ('dmacxc_perms_datanalys', 'DMA\u4ea7\u9500\u5dee\u5206\u6790'), ('dmacxc_perms_datanalys_edit', 'DMA\u4ea7\u9500\u5dee\u5206\u6790_\u53ef\u5199'), ('flownalys_perms_datanalys', '\u6d41\u91cf\u5206\u6790'), ('flownalys_perms_datanalys_edit', '\u6d41\u91cf\u5206\u6790_\u53ef\u5199'), ('comparenalys_perms_datanalys', '\u5bf9\u6bd4\u5206\u6790'), ('comparenalys_perms_datanalys_edit', '\u5bf9\u6bd4\u5206\u6790_\u53ef\u5199'), ('peibiao_perms_datanalys', '\u914d\u8868\u5206\u6790'), ('peibiao_perms_datanalys_edit', '\u914d\u8868\u5206\u6790_\u53ef\u5199'), ('rawdata_perms_datanalys', '\u539f\u59cb\u6570\u636e'), ('rawdata_perms_datanalys_edit', '\u539f\u59cb\u6570\u636e_\u53ef\u5199'), ('mnf_perms_datanalys', '\u591c\u95f4\u6700\u5c0f\u6d41\u91cf'), ('mnf_perms_datanalys_edit', '\u591c\u95f4\u6700\u5c0f\u6d41\u91cf_\u53ef\u5199'), ('perms_alarmcenter', '\u62a5\u8b66\u4e2d\u5fc3'), ('stationalarm_perms_alarmcenter', '\u7ad9\u70b9\u62a5\u8b66\u8bbe\u7f6e'), ('stationalarm_perms_alarmcenter_edit', '\u7ad9\u70b9\u62a5\u8b66\u8bbe\u7f6e_\u53ef\u5199'), ('dmaalarm_perms_alarmcenter', 'DMA\u62a5\u8b66\u8bbe\u7f6e'), ('dmaalarm_perms_alarmcenter_edit', 'DMA\u62a5\u8b66\u8bbe\u7f6e_\u53ef\u5199'), ('queryalarm_perms_alarmcenter', '\u62a5\u8b66\u67e5\u8be2'), ('queryalarm_perms_alarmcenter_edit', '\u62a5\u8b66\u67e5\u8be2_\u53ef\u5199'), ('perms_basemanager', '\u57fa\u7840\u7ba1\u7406'), ('dmamanager_perms_basemanager', 'dma\u7ba1\u7406'), ('dmamanager_perms_basemanager_edit', 'dma\u7ba1\u7406_\u53ef\u5199'), ('stationmanager_perms_basemanager', '\u7ad9\u70b9\u7ba1\u7406'), ('stationmanager_perms_basemanager_edit', '\u7ad9\u70b9\u7ba1\u7406_\u53ef\u5199'), ('perms_firmmanager', '\u4f01\u4e1a\u7ba1\u7406'), ('rolemanager_perms_firmmanager', '\u89d2\u8272\u7ba1\u7406'), ('rolemanager_perms_firmmanager_edit', '\u89d2\u8272\u7ba1\u7406_\u53ef\u5199'), ('organusermanager_perms_basemanager', '\u7ec4\u7ec7\u548c\u7528\u6237\u7ba1\u7406'), ('organusermanager_perms_basemanager_edit', '\u7ec4\u7ec7\u548c\u7528\u6237\u7ba1\u7406_\u53ef\u5199'), ('perms_devicemanager', '\u8bbe\u5907\u7ba1\u7406'), ('meters_perms_devicemanager', '\u8868\u5177\u7ba1\u7406'), ('meters_perms_devicemanager_edit', '\u8868\u5177\u7ba1\u7406_\u53ef\u5199'), ('simcard_perms_devicemanager', 'SIM\u5361\u7ba1\u7406'), ('simcard_perms_devicemanager_edit', 'SIM\u5361\u7ba1\u7406_\u53ef\u5199'), ('params_perms_devicemanager', '\u53c2\u6570\u6307\u4ee4'), ('params_perms_devicemanager_edit', '\u53c2\u6570\u6307\u4ee4_\u53ef\u5199'), ('perms_basenalys', '\u57fa\u51c6\u5206\u6790'), ('dma_perms_basenalys', 'DMA\u57fa\u51c6\u5206\u6790'), ('dma_perms_basenalys_edit', 'DMA\u57fa\u51c6\u5206\u6790_\u53ef\u5199'), ('mf_perms_basenalys', '\u6700\u5c0f\u6d41\u91cf\u5206\u6790'), ('mf_perms_basenalys_edit', '\u6700\u5c0f\u6d41\u91cf\u5206\u6790_\u53ef\u5199'), ('day_perms_basenalys', '\u65e5\u57fa\u51c6\u6d41\u91cf\u5206\u6790'), ('day_perms_basenalys_edit', '\u65e5\u57fa\u51c6\u6d41\u91cf\u5206\u6790_\u53ef\u5199'), ('perms_reporttable', '\u7edf\u8ba1\u62a5\u8868'), ('querylog_perms_reporttable', '\u65e5\u5fd7\u67e5\u8be2'), ('querylog_perms_reporttable_edit', '\u65e5\u5fd7\u67e5\u8be2_\u53ef\u5199'), ('alarm_perms_reporttable', '\u62a5\u8b66\u62a5\u8868'), ('alarm_perms_reporttable_edit', '\u62a5\u8b66\u62a5\u8868_\u53ef\u5199'), ('dmastatics_perms_reporttable', 'DMA\u7edf\u8ba1\u62a5\u8868'), ('dmastatics_perms_reporttable_edit', 'DMA\u7edf\u8ba1\u62a5\u8868_\u53ef\u5199'), ('biguser_perms_reporttable', '\u5927\u7528\u6237\u62a5\u8868'), ('biguser_perms_reporttable_edit', '\u5927\u7528\u6237\u62a5\u8868_\u53ef\u5199'), ('flows_perms_reporttable', '\u6d41\u91cf\u62a5\u8868'), ('flows_perms_reporttable_edit', '\u6d41\u91cf\u62a5\u8868_\u53ef\u5199'), ('waters_perms_reporttable', '\u6c34\u91cf\u62a5\u8868'), ('waters_perms_reporttable_edit', '\u6c34\u91cf\u62a5\u8868_\u53ef\u5199'), ('biaowu_perms_reporttable', '\u8868\u52a1\u62a5\u8868'), ('biaowu_perms_reporttable_edit', '\u8868\u52a1\u62a5\u8868_\u53ef\u5199'), ('bigdata_perms_reporttable', '\u5927\u6570\u636e\u62a5\u8868'), ('bigdata_perms_reporttable_edit', '\u5927\u6570\u636e\u62a5\u8868_\u53ef\u5199'), ('perms_systemconfig', '\u7cfb\u7edf\u7ba1\u7406'), ('personality_perms_systemconfig', '\u5e73\u53f0\u4e2a\u6027\u5316\u7ba1\u7406'), ('personality_perms_systemconfig_edit', '\u5e73\u53f0\u4e2a\u6027\u5316\u7ba1\u7406_\u53ef\u5199'), ('system_perms_systemconfig', '\u7cfb\u7edf\u8bbe\u7f6e'), ('system_perms_systemconfig_edit', '\u7cfb\u7edf\u8bbe\u7f6e_\u53ef\u5199'), ('retransit_perms_systemconfig', '\u8f6c\u53d1\u8bbe\u7f6e'), ('retransit_perms_systemconfig_edit', '\u8f6c\u53d1\u8bbe\u7f6e_\u53ef\u5199'), ('icons_perms_systemconfig', '\u56fe\u6807\u914d\u7f6e'), ('icons_perms_systemconfig_edit', '\u56fe\u6807\u914d\u7f6e_\u53ef\u5199'), ('querylog_perms_systemconfig', '\u65e5\u5fd7\u67e5\u8be2'), ('querylog_perms_systemconfig_edit', '\u65e5\u5fd7\u67e5\u8be2_\u53ef\u5199')),
            },
        ),
    ]
