# Generated by Django 2.0 on 2019-07-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizations',
            name='is_org',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
