# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-04 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entm', '0002_auto_20180604_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizations',
            name='register_date',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='\u6ce8\u518c\u65e5\u671f'),
        ),
    ]
