# Generated by Django 2.0 on 2018-11-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entm', '0002_auto_20180826_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizations',
            name='city',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='organizations',
            name='coorType',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='organizations',
            name='district',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='organizations',
            name='islocation',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='organizations',
            name='latitude',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='organizations',
            name='location',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='organizations',
            name='longitude',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='organizations',
            name='province',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='organizations',
            name='zoomIn',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
