# Generated by Django 2.0 on 2018-11-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entm', '0003_auto_20181113_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizations',
            name='adcode',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='organizations',
            name='districtlevel',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
