# Generated by Django 2.0.8 on 2018-08-19 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DMABaseinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dma_no', models.CharField(max_length=50, unique=True, verbose_name='分区编号')),
                ('dma_name', models.CharField(max_length=50, unique=True, verbose_name='分区名称')),
                ('pepoles_num', models.CharField(blank=True, max_length=50, null=True, verbose_name='服务人口')),
                ('acreage', models.CharField(blank=True, max_length=50, null=True, verbose_name='服务面积')),
                ('user_num', models.CharField(blank=True, max_length=50, null=True, verbose_name='用户数量')),
                ('pipe_texture', models.CharField(blank=True, max_length=50, null=True, verbose_name='管道材质')),
                ('pipe_length', models.CharField(blank=True, max_length=50, null=True, verbose_name='管道总长度(m)')),
                ('pipe_links', models.CharField(blank=True, max_length=50, null=True, verbose_name='管道连接总数(个)')),
                ('pipe_years', models.CharField(blank=True, max_length=50, null=True, verbose_name='管道最长服务年限(年)')),
                ('pipe_private', models.CharField(blank=True, max_length=50, null=True, verbose_name='私人拥有水管长度(m)')),
                ('ifc', models.CharField(blank=True, max_length=250, null=True, verbose_name='IFC参数')),
                ('aznp', models.CharField(blank=True, max_length=250, null=True, verbose_name='AZNP')),
                ('night_use', models.CharField(blank=True, max_length=50, null=True, verbose_name='正常夜间用水量')),
                ('cxc_value', models.CharField(blank=True, max_length=50, null=True, verbose_name='产销差目标值')),
                ('creator', models.CharField(blank=True, max_length=50, null=True, verbose_name='负责人')),
                ('create_date', models.CharField(blank=True, max_length=30, null=True, verbose_name='建立日期')),
                ('belongto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dma', to='entm.Organizations')),
            ],
            options={
                'managed': True,
                'db_table': 'dmabaseinfo',
            },
        ),
        migrations.CreateModel(
            name='DmaStations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(max_length=30)),
                ('meter_type', models.CharField(max_length=30)),
                ('dmaid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dmastation', to='dmam.DMABaseinfo')),
            ],
            options={
                'managed': True,
                'db_table': 'dmastations',
            },
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialnumber', models.CharField(blank=True, db_column='SerialNumber', max_length=30, null=True)),
                ('version', models.CharField(blank=True, db_column='version', max_length=30, null=True)),
                ('dn', models.CharField(blank=True, db_column='Dn', max_length=30, null=True)),
                ('metertype', models.CharField(blank=True, db_column='MeterType', max_length=30, null=True)),
                ('mtype', models.CharField(blank=True, db_column='Type', max_length=30, null=True)),
                ('manufacturer', models.CharField(blank=True, db_column='Manufacturer', max_length=30, null=True)),
                ('protocol', models.CharField(blank=True, db_column='Protocol', max_length=64, null=True)),
                ('R', models.CharField(blank=True, db_column='R', max_length=64, null=True)),
                ('q4', models.CharField(blank=True, db_column='Q4', max_length=64, null=True)),
                ('q3', models.CharField(blank=True, db_column='Q3', max_length=64, null=True)),
                ('q2', models.CharField(blank=True, db_column='Q2', max_length=64, null=True)),
                ('q1', models.CharField(blank=True, db_column='Q1', max_length=64, null=True)),
                ('check_cycle', models.CharField(blank=True, db_column='check cycle', max_length=64, null=True)),
                ('state', models.CharField(blank=True, db_column='state', max_length=64, null=True)),
                ('tcpresendcount', models.CharField(blank=True, db_column='tcpresendcount', max_length=64, null=True)),
                ('tcpresponovertime', models.CharField(blank=True, db_column='tcpresponovertime', max_length=64, null=True)),
                ('udpresendcount', models.CharField(blank=True, db_column='udpresendcount', max_length=64, null=True)),
                ('udpresponovertime', models.CharField(blank=True, db_column='udpresponovertime', max_length=64, null=True)),
                ('smsresendcount', models.CharField(blank=True, db_column='smsresendcount', max_length=64, null=True)),
                ('smsresponovertime', models.CharField(blank=True, db_column='smsresponovertime', max_length=64, null=True)),
                ('heartbeatperiod', models.CharField(blank=True, db_column='heartbeatperiod', max_length=64, null=True)),
                ('ipaddr', models.CharField(blank=True, db_column='ipaddr', max_length=64, null=True)),
                ('port', models.CharField(blank=True, db_column='port', max_length=64, null=True)),
                ('entrypoint', models.CharField(blank=True, db_column='entrypoint', max_length=64, null=True)),
                ('flowzerovalue', models.CharField(blank=True, db_column='flowzerovalue', max_length=64, null=True)),
                ('updatastarttime', models.CharField(blank=True, db_column='updatastarttime', max_length=64, null=True)),
                ('updatamode', models.CharField(blank=True, db_column='updatamode', max_length=64, null=True)),
                ('collectperiod', models.CharField(blank=True, db_column='collectperiod', max_length=64, null=True)),
                ('updataperiod', models.CharField(blank=True, db_column='updataperiod', max_length=64, null=True)),
                ('updatatime1', models.CharField(blank=True, db_column='updatatime1', max_length=64, null=True)),
                ('updatatime2', models.CharField(blank=True, db_column='updatatime2', max_length=64, null=True)),
                ('updatatime3', models.CharField(blank=True, db_column='updatatime3', max_length=64, null=True)),
                ('updatatime4', models.CharField(blank=True, db_column='updatatime4', max_length=64, null=True)),
                ('transimeterfactor', models.CharField(blank=True, db_column='transimeterfactor', max_length=64, null=True)),
                ('manufacturercode', models.CharField(blank=True, db_column='manufacturercode', max_length=64, null=True)),
                ('smallsignalcutpoint', models.CharField(blank=True, db_column='smallsignalcutpoint', max_length=64, null=True)),
                ('pressurepermit', models.CharField(blank=True, db_column='pressurepermit', max_length=64, null=True)),
                ('flowdorient', models.CharField(blank=True, db_column='flowdorient', max_length=64, null=True)),
                ('maintaindate', models.CharField(blank=True, db_column='maintaindate', max_length=64, null=True)),
                ('plusaccumupreset', models.CharField(blank=True, db_column='plusaccumupreset', max_length=64, null=True)),
                ('flowmeasureunit', models.CharField(blank=True, db_column='flowmeasureunit', max_length=64, null=True)),
                ('belongto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entm.Organizations')),
            ],
            options={
                'managed': True,
                'db_table': 'meter',
            },
        ),
        migrations.CreateModel(
            name='SimCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simcardNumber', models.CharField(blank=True, db_column='SIMID', max_length=30, null=True)),
                ('isStart', models.CharField(blank=True, db_column='state', max_length=64, null=True)),
                ('iccid', models.CharField(blank=True, db_column='ICCID', max_length=30, null=True)),
                ('imei', models.CharField(blank=True, db_column='IMEI', max_length=30, null=True)),
                ('imsi', models.CharField(blank=True, db_column='IMSI', max_length=30, null=True)),
                ('operator', models.CharField(blank=True, db_column='operator', max_length=30, null=True)),
                ('simFlow', models.CharField(blank=True, db_column='simFlow', max_length=30, null=True)),
                ('openCardTime', models.CharField(blank=True, db_column='openCardTime', max_length=64, null=True)),
                ('endTime', models.CharField(blank=True, db_column='endTime', max_length=64, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, db_column='create_date')),
                ('update_date', models.DateTimeField(auto_now=True, db_column='update_date')),
                ('remark', models.CharField(blank=True, db_column='remark', max_length=64, null=True)),
                ('belongto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entm.Organizations')),
            ],
            options={
                'managed': True,
                'db_table': 'simcard',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, db_column='UserName', max_length=30, null=True)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=30, null=True)),
                ('usertype', models.CharField(blank=True, db_column='UserType', max_length=128, null=True)),
                ('madedate', models.CharField(blank=True, db_column='MadeDate', max_length=30, null=True)),
                ('lng', models.CharField(blank=True, db_column='Lng', max_length=30, null=True)),
                ('lat', models.CharField(blank=True, db_column='Lat', max_length=30, null=True)),
                ('coortype', models.CharField(blank=True, db_column='CoorType', max_length=30, null=True)),
                ('biguser', models.CharField(blank=True, db_column='biguser', max_length=30, null=True)),
                ('focus', models.CharField(blank=True, db_column='focus', max_length=30, null=True)),
                ('locate', models.CharField(blank=True, db_column='locate', max_length=30, null=True)),
                ('dmametertype', models.CharField(blank=True, db_column='MeterType', max_length=30, null=True)),
                ('belongto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entm.Organizations')),
                ('dmaid', models.ManyToManyField(to='dmam.DMABaseinfo')),
                ('meter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dmam.Meter')),
            ],
            options={
                'managed': True,
                'db_table': 'station',
            },
        ),
        migrations.CreateModel(
            name='WaterUserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usertype', models.CharField(max_length=256)),
                ('explains', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'managed': True,
                'db_table': 'waterusertype',
            },
        ),
        migrations.AddField(
            model_name='meter',
            name='simid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meter', to='dmam.SimCard'),
        ),
        migrations.AlterUniqueTogether(
            name='dmabaseinfo',
            unique_together={('dma_no',)},
        ),
    ]
