# Generated by Django 2.0 on 2019-07-23 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0002_auto_20190723_1538'),
        ('dmam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='bigmeter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='legacy.Bigmeter'),
        ),
    ]
