# Generated by Django 2.0.5 on 2018-07-25 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entm', '0001_initial'),
        ('dmam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialnumber', models.CharField(blank=True, db_column='SerialNumber', max_length=30, null=True)),
                ('simid', models.CharField(blank=True, db_column='SIMID', max_length=30, null=True)),
                ('version', models.CharField(blank=True, db_column='version', max_length=30, null=True)),
                ('dn', models.CharField(blank=True, db_column='Dn', max_length=30, null=True)),
                ('metertype', models.CharField(blank=True, db_column='MeterType', max_length=30, null=True)),
                ('mtype', models.CharField(blank=True, db_column='Type', max_length=30, null=True)),
                ('manufacturer', models.CharField(blank=True, db_column='Manufacturer', max_length=30, null=True)),
                ('protocol', models.CharField(blank=True, db_column='Protocol', max_length=64, null=True)),
                ('R', models.CharField(blank=True, db_column='R', max_length=64, null=True)),
                ('q3', models.CharField(blank=True, db_column='Q3', max_length=64, null=True)),
                ('q1', models.CharField(blank=True, db_column='Q1', max_length=64, null=True)),
                ('check_cycle', models.CharField(blank=True, db_column='check cycle', max_length=64, null=True)),
                ('state', models.CharField(blank=True, db_column='state', max_length=64, null=True)),
                ('belongto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meter', to='entm.Organizations')),
            ],
            options={
                'db_table': 'meter',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('username', models.CharField(blank=True, db_column='UserName', max_length=30, null=True)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=30, null=True)),
                ('usertype', models.CharField(blank=True, db_column='UserType', max_length=128, null=True)),
                ('madedate', models.CharField(blank=True, db_column='MadeDate', max_length=30, null=True)),
                ('lng', models.CharField(blank=True, db_column='Lng', max_length=30, null=True)),
                ('lat', models.CharField(blank=True, db_column='Lat', max_length=30, null=True)),
                ('coortype', models.CharField(blank=True, db_column='CoorType', max_length=30, null=True)),
                ('commaddr', models.CharField(db_column='CommAddr', max_length=30, primary_key=True, serialize=False)),
                ('biguser', models.CharField(blank=True, db_column='biguser', max_length=30, null=True)),
                ('focus', models.CharField(blank=True, db_column='focus', max_length=30, null=True)),
                ('locate', models.CharField(blank=True, db_column='locate', max_length=30, null=True)),
                ('belongto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station', to='entm.Organizations')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station', to='dmam.Meter')),
            ],
            options={
                'db_table': 'station',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='dmabaseinfo',
            name='create_date',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='建立日期'),
        ),
    ]
