# Generated by Django 2.0 on 2018-10-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmam', '0002_vcommunity_vconcentrator_vwatermeter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vwatermeter',
            name='waterid',
            field=models.IntegerField(blank=True, db_column='WaterId', null=True),
        ),
    ]
