# Generated by Django 2.0.5 on 2018-07-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmam', '0002_auto_20180725_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='commaddr',
        ),
        migrations.AddField(
            model_name='station',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
