# Generated by Django 2.0.5 on 2018-08-02 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dmam', '0003_auto_20180801_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='belongto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entm.Organizations'),
        ),
        migrations.AlterField(
            model_name='meter',
            name='simid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meter', to='dmam.SimCard'),
        ),
        migrations.AlterField(
            model_name='simcard',
            name='belongto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entm.Organizations'),
        ),
        migrations.AlterField(
            model_name='station',
            name='belongto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entm.Organizations'),
        ),
        migrations.AlterField(
            model_name='station',
            name='meter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dmam.Meter'),
        ),
    ]
