# Generated by Django 2.0.5 on 2018-07-26 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dmam', '0003_auto_20180725_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='dmaid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='station', to='dmam.DMABaseinfo'),
        ),
    ]
