# Generated by Django 2.0.5 on 2018-08-02 11:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dmam', '0004_auto_20180802_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simcard',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, db_column='create_date', default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='simcard',
            name='update_date',
            field=models.DateTimeField(auto_now=True, db_column='update_date'),
        ),
    ]
