# Generated by Django 2.0.5 on 2018-07-29 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmam', '0004_station_dmaid'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='dmametertype',
            field=models.CharField(blank=True, db_column='MeterType', max_length=30, null=True),
        ),
    ]
