# Generated by Django 2.0.5 on 2018-07-30 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entm', '0001_initial'),
        ('dmam', '0005_station_dmametertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simcardNumber', models.CharField(blank=True, db_column='SIMID', max_length=30, null=True)),
                ('isStart', models.CharField(blank=True, db_column='state', max_length=64, null=True)),
                ('iccid', models.CharField(blank=True, db_column='ICCID', max_length=30, null=True)),
                ('imei', models.CharField(blank=True, db_column='IMEI', max_length=30, null=True)),
                ('imsi', models.CharField(blank=True, db_column='IMSI', max_length=30, null=True)),
                ('operator', models.CharField(blank=True, db_column='operator', max_length=30, null=True)),
                ('simFlow', models.CharField(blank=True, db_column='simFlow', max_length=30, null=True)),
                ('openCardTime', models.CharField(blank=True, db_column='openCardTime', max_length=64, null=True)),
                ('endTime', models.CharField(blank=True, db_column='endTime', max_length=64, null=True)),
                ('create_date', models.CharField(blank=True, db_column='create_date', max_length=64, null=True)),
                ('update_date', models.CharField(blank=True, db_column='update_date', max_length=64, null=True)),
                ('remark', models.CharField(blank=True, db_column='remark', max_length=64, null=True)),
                ('belongto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simcard', to='entm.Organizations')),
            ],
            options={
                'db_table': 'simcard',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='meter',
            name='simid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='meter', to='dmam.SimCard'),
            preserve_default=False,
        ),
    ]
