# Generated by Django 2.0.5 on 2018-08-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmam', '0005_auto_20180802_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='collectperiod',
            field=models.CharField(blank=True, db_column='collectperiod', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='meter',
            name='entrypoint',
            field=models.CharField(blank=True, db_column='entrypoint', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='meter',
            name='flowdorient',
            field=models.CharField(blank=True, db_column='flowdorient', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='meter',
            name='flowmeasureunit',
            field=models.CharField(blank=True, db_column='flowmeasureunit', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='meter',
            name='flowzerovalue',
            field=models.CharField(blank=True, db_column='flowzerovalue', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='meter',
            name='heartbeatperiod',
            field=models.CharField(blank=True, db_column='heartbeatperiod', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='meter',
            name='ipaddr',
            field=models.CharField(blank=True, db_column='ipaddr', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='meter',
            name='maintaindate',
            field=models.CharField(blank=True, db_column='maintaindate', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='meter',
            name='manufacturercode',
            field=models.CharField(blank=True, db_column='manufacturercode', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='meter',
            name='plusaccumupreset',
            field=models.CharField(blank=True, db_column='plusaccumupreset', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='meter',
            name='port',
            field=models.CharField(blank=True, db_column='port', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='meter',
            name='pressurepermit',
            field=models.CharField(blank=True, db_column='pressurepermit', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='meter',
            name='q2',
            field=models.CharField(blank=True, db_column='Q2', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='meter',
            name='smallsignalcutpoint',
            field=models.CharField(blank=True, db_column='smallsignalcutpoint', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='meter',
            name='smsresendcount',
            field=models.CharField(blank=True, db_column='smsresendcount', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='meter',
            name='smsresponovertime',
            field=models.CharField(blank=True, db_column='smsresponovertime', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='meter',
            name='tcpresendcount',
            field=models.CharField(blank=True, db_column='tcpresendcount', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='meter',
            name='tcpresponovertime',
            field=models.CharField(blank=True, db_column='tcpresponovertime', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='meter',
            name='transimeterfactor',
            field=models.CharField(blank=True, db_column='transimeterfactor', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='meter',
            name='udpresendcount',
            field=models.CharField(blank=True, db_column='udpresendcount', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='meter',
            name='udpresponovertime',
            field=models.CharField(blank=True, db_column='udpresponovertime', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='meter',
            name='updatamode',
            field=models.CharField(blank=True, db_column='updatamode', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='meter',
            name='updataperiod',
            field=models.CharField(blank=True, db_column='updataperiod', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='meter',
            name='updatastarttime',
            field=models.CharField(blank=True, db_column='updatastarttime', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='meter',
            name='updatatime1',
            field=models.CharField(blank=True, db_column='updatatime1', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='meter',
            name='updatatime2',
            field=models.CharField(blank=True, db_column='updatatime2', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='meter',
            name='updatatime3',
            field=models.CharField(blank=True, db_column='updatatime3', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='meter',
            name='updatatime4',
            field=models.CharField(blank=True, db_column='updatatime4', max_length=64, null=True),
        ),
    ]
