# Generated by Django 2.0.5 on 2018-08-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmam', '0006_auto_20180814_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='q4',
            field=models.CharField(blank=True, db_column='Q4', max_length=64, null=True),
        ),
    ]
