# Generated by Django 2.0 on 2018-11-20 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dmam', '0009_auto_20181107_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vconcentrator',
            name='communityid',
        ),
        migrations.AddField(
            model_name='vcommunity',
            name='vconcentrators',
            field=models.ManyToManyField(to='dmam.VConcentrator'),
        ),
        migrations.AddField(
            model_name='vconcentrator',
            name='coortype',
            field=models.CharField(blank=True, db_column='CoorType', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='vconcentrator',
            name='lat',
            field=models.CharField(blank=True, db_column='Lat', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='vconcentrator',
            name='lng',
            field=models.CharField(blank=True, db_column='Lng', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='vconcentrator',
            name='madedate',
            field=models.CharField(blank=True, db_column='MadeDate', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='vconcentrator',
            name='manufacturer',
            field=models.CharField(blank=True, db_column='Manufacturer', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='vconcentrator',
            name='model',
            field=models.CharField(blank=True, db_column='Model', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='vconcentrator',
            name='serialnumber',
            field=models.CharField(blank=True, db_column='SerialNumber', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='vwatermeter',
            name='ValveMeter',
            field=models.CharField(blank=True, db_column='ValveMeter', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='vwatermeter',
            name='buildingname',
            field=models.CharField(blank=True, db_column='BuildingName', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='vwatermeter',
            name='concentrator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dmam.VConcentrator'),
        ),
        migrations.AddField(
            model_name='vwatermeter',
            name='madedate',
            field=models.CharField(blank=True, db_column='MadeDate', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='vwatermeter',
            name='manufacturer',
            field=models.CharField(blank=True, db_column='Manufacturer', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='vwatermeter',
            name='nodeaddr',
            field=models.CharField(blank=True, db_column='NodeAddr', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='vwatermeter',
            name='numbersth',
            field=models.CharField(blank=True, db_column='NumberSth', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='vwatermeter',
            name='roomname',
            field=models.CharField(blank=True, db_column='RoomName', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='vwatermeter',
            name='serialnumber',
            field=models.CharField(blank=True, db_column='SerialNumber', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='vwatermeter',
            name='username',
            field=models.CharField(blank=True, db_column='UserName', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='vwatermeter',
            name='usertel',
            field=models.CharField(blank=True, db_column='UserTel', max_length=30, null=True),
        ),
    ]
