# Generated by Django 2.0 on 2018-11-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmam', '0011_vwatermeter_dn'),
    ]

    operations = [
        migrations.AddField(
            model_name='vconcentrator',
            name='address',
            field=models.CharField(blank=True, db_column='Address', max_length=128, null=True),
        ),
    ]
