# Generated by Django 2.0 on 2018-11-21 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dmam', '0012_vconcentrator_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vcommunity',
            name='belongto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entm.Organizations'),
        ),
        migrations.AlterField(
            model_name='vconcentrator',
            name='belongto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entm.Organizations'),
        ),
        migrations.AlterField(
            model_name='vwatermeter',
            name='belongto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entm.Organizations'),
        ),
    ]
