# Generated by Django 2.0 on 2018-11-21 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmam', '0013_auto_20181121_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='vwatermeter',
            name='installationsite',
            field=models.CharField(blank=True, db_column='InstallationSite', max_length=30, null=True),
        ),
    ]
