# Generated by Django 2.0 on 2018-12-05 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entm', '0005_organizations_organlevel'),
        ('dmam', '0014_vwatermeter_installationsite'),
    ]

    operations = [
        migrations.CreateModel(
            name='VPressure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, db_column='Name', max_length=64, null=True)),
                ('serialnumber', models.CharField(blank=True, db_column='SerialNumber', max_length=30, null=True)),
                ('version', models.CharField(blank=True, db_column='version', max_length=30, null=True)),
                ('dn', models.CharField(blank=True, db_column='Dn', max_length=30, null=True)),
                ('metertype', models.CharField(blank=True, db_column='MeterType', max_length=30, null=True)),
                ('mtype', models.CharField(blank=True, db_column='Type', max_length=30, null=True)),
                ('manufacturer', models.CharField(blank=True, db_column='Manufacturer', max_length=30, null=True)),
                ('protocol', models.CharField(blank=True, db_column='Protocol', max_length=64, null=True)),
                ('lng', models.CharField(blank=True, db_column='Lng', max_length=30, null=True)),
                ('lat', models.CharField(blank=True, db_column='Lat', max_length=30, null=True)),
                ('coortype', models.CharField(blank=True, db_column='CoorType', max_length=30, null=True)),
                ('check_cycle', models.CharField(blank=True, db_column='check cycle', max_length=64, null=True)),
                ('state', models.CharField(blank=True, db_column='state', max_length=64, null=True)),
                ('belongto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entm.Organizations')),
                ('simid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dmam.SimCard')),
            ],
            options={
                'db_table': 'vpressure',
                'managed': True,
            },
        ),
    ]
