# Generated by Django 2.0 on 2018-12-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmam', '0016_vsecondwater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vsecondwater',
            name='name',
            field=models.CharField(db_column='Name', max_length=64, unique=True),
        ),
    ]
