# Generated by Django 2.0 on 2019-01-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmam', '0017_auto_20181214_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='vcommunity',
            name='outter',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='vwatermeter',
            name='outter',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
