# Generated by Django 2.0 on 2019-01-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmam', '0018_auto_20190115_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='vwatermeter',
            name='outter_communityid',
            field=models.IntegerField(blank=True, db_column='sx_wm_communityid', null=True),
        ),
    ]
