# Generated by Django 2.0 on 2019-01-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmam', '0019_vwatermeter_outter_communityid'),
    ]

    operations = [
        migrations.AddField(
            model_name='vcommunity',
            name='amrs_commutid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vwatermeter',
            name='amrs_waterid',
            field=models.IntegerField(blank=True, db_column='Amrs WaterId', null=True),
        ),
    ]
