# Generated by Django 2.0 on 2018-11-08 23:47

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FenceDistrict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='区域名称')),
                ('ftype', models.CharField(blank=True, max_length=30, null=True, verbose_name='区域类型')),
                ('createDataTime', models.CharField(blank=True, max_length=30, null=True, verbose_name='创建时间')),
                ('updateDataTime', models.CharField(blank=True, max_length=30, null=True, verbose_name='修改时间')),
                ('createDataUsername', models.CharField(blank=True, max_length=30, null=True, verbose_name='创建人')),
                ('updateDataUsername', models.CharField(blank=True, max_length=30, null=True, verbose_name='修改人')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('cid', models.CharField(blank=True, max_length=100, null=True)),
                ('pId', models.CharField(blank=True, max_length=100, null=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='gis.FenceDistrict')),
            ],
            options={
                'db_table': 'fencedistrict',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Polygon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polygonId', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='区域名称')),
                ('ftype', models.CharField(blank=True, max_length=30, null=True, verbose_name='区域类型')),
                ('shape', models.CharField(blank=True, max_length=30, null=True, verbose_name='形状')),
                ('pointSeqs', models.TextField()),
                ('longitudes', models.TextField()),
                ('latitudes', models.TextField()),
                ('dma_no', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'polygon',
                'managed': True,
            },
        ),
    ]
