# Generated by Django 2.0 on 2018-11-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FenceShape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shapeId', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='区域名称')),
                ('zonetype', models.CharField(blank=True, max_length=30, null=True, verbose_name='区域类型')),
                ('shape', models.CharField(blank=True, max_length=30, null=True, verbose_name='形状')),
                ('pointSeqs', models.TextField()),
                ('longitudes', models.TextField()),
                ('latitudes', models.TextField()),
                ('lnglatQuery_LU', models.CharField(blank=True, max_length=30, null=True)),
                ('lnglatQuery_RD', models.CharField(blank=True, max_length=30, null=True)),
                ('centerPointLat', models.CharField(blank=True, max_length=30, null=True)),
                ('centerPointLng', models.CharField(blank=True, max_length=30, null=True)),
                ('centerRadius', models.CharField(blank=True, max_length=30, null=True)),
                ('province', models.CharField(blank=True, max_length=30, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('district', models.CharField(blank=True, max_length=30, null=True)),
                ('strokeColor', models.CharField(blank=True, max_length=100, null=True)),
                ('fillColor', models.CharField(blank=True, max_length=100, null=True)),
                ('dma_no', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'fenceshape',
                'managed': True,
            },
        ),
    ]
